truncate category_parent;
truncate category;
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (1,  NULL, '1', 1, NULL, '0', "﻿Одежда");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (1, 0);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (16,  NULL, '1', 16, NULL, '0', "Женщинам");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (16, 1);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (52,  NULL, '1', 52, NULL, '0', "Платья ");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (52, 16);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (53,  NULL, '1', 53, NULL, '0', "Блузки и рубашки");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (53, 16);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (54,  NULL, '1', 54, NULL, '0', "Комбинезоны");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (54, 16);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (55,  NULL, '1', 55, NULL, '0', "Футболки ");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (55, 16);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (56,  NULL, '1', 56, NULL, '0', "Топы");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (56, 16);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (57,  NULL, '1', 57, NULL, '0', "Майки");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (57, 16);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (58,  NULL, '1', 58, NULL, '0', "Брюки ");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (58, 16);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (59,  NULL, '1', 59, NULL, '0', "Одежда с принтами");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (59, 16);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (60,  NULL, '1', 60, NULL, '0', "Шорты ");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (60, 16);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (61,  NULL, '1', 61, NULL, '0', "Легинсы");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (61, 16);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (62,  NULL, '1', 62, NULL, '0', "Юбки");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (62, 16);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (63,  NULL, '1', 63, NULL, '0', "Джинсы");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (63, 16);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (64,  NULL, '1', 64, NULL, '0', "Куртки");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (64, 16);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (65,  NULL, '1', 65, NULL, '0', "Шубы");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (65, 16);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (66,  NULL, '1', 66, NULL, '0', "Спортивные куртки");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (66, 16);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (67,  NULL, '1', 67, NULL, '0', "Толстовки и кофты");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (67, 16);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (68,  NULL, '1', 68, NULL, '0', "Кардиган");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (68, 16);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (69,  NULL, '1', 69, NULL, '0', "Пуловер");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (69, 16);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (70,  NULL, '1', 70, NULL, '0', "Спортивный костюм");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (70, 16);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (71,  NULL, '1', 71, NULL, '0', "Купальники");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (71, 16);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (72,  NULL, '1', 72, NULL, '0', "Плаяжная одежда");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (72, 16);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (17,  NULL, '1', 17, NULL, '0', "Женское нижнее белье");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (17, 1);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (73,  NULL, '1', 73, NULL, '0', "Комплекты");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (73, 17);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (74,  NULL, '1', 74, NULL, '0', "Бюстгальтер");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (74, 17);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (75,  NULL, '1', 75, NULL, '0', "Трусы");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (75, 17);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (76,  NULL, '1', 76, NULL, '0', "Пижама");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (76, 17);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (77,  NULL, '1', 77, NULL, '0', "Теплое нательное белье");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (77, 17);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (78,  NULL, '1', 78, NULL, '0', "Спортивное белье");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (78, 17);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (79,  NULL, '1', 79, NULL, '0', "Поддерживающее белье");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (79, 17);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (80,  NULL, '1', 80, NULL, '0', "Чулки колготки");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (80, 17);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (81,  NULL, '1', 81, NULL, '0', "Носки");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (81, 17);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (82,  NULL, '1', 82, NULL, '0', "Эротическое белье");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (82, 17);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (83,  NULL, '1', 83, NULL, '0', "Термо белье");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (83, 17);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (18,  NULL, '1', 18, NULL, '0', "Мужчинам");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (18, 1);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (84,  NULL, '1', 84, NULL, '0', "Футболки и майки");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (84, 18);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (85,  NULL, '1', 85, NULL, '0', "Поло");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (85, 18);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (86,  NULL, '1', 86, NULL, '0', "Спортивный костюм");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (86, 18);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (87,  NULL, '1', 87, NULL, '0', "Толстовки и кофты");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (87, 18);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (88,  NULL, '1', 88, NULL, '0', "Кардиган");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (88, 18);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (89,  NULL, '1', 89, NULL, '0', "Костюмы и пиджаки");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (89, 18);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (90,  NULL, '1', 90, NULL, '0', "Штаны повседневные");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (90, 18);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (91,  NULL, '1', 91, NULL, '0', "Шорты");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (91, 18);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (92,  NULL, '1', 92, NULL, '0', "Пляж");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (92, 18);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (93,  NULL, '1', 93, NULL, '0', "Джинсы");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (93, 18);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (94,  NULL, '1', 94, NULL, '0', "Рубашки");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (94, 18);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (95,  NULL, '1', 95, NULL, '0', "Нижнее белье");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (95, 18);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (96,  NULL, '1', 96, NULL, '0', "Носки");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (96, 18);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (97,  NULL, '1', 97, NULL, '0', "Термо белье");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (97, 18);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (98,  NULL, '1', 98, NULL, '0', "Куртки");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (98, 18);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (99,  NULL, '1', 99, NULL, '0', "Куртки спортивные");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (99, 18);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (100,  NULL, '1', 100, NULL, '0', "Пальто");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (100, 18);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (2,  NULL, '1', 2, NULL, '0', "Обувь сумки аксессуары");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (2, 0);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (19,  NULL, '1', 19, NULL, '0', "Женская");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (19, 2);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (101,  NULL, '1', 101, NULL, '0', "Туфли");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (101, 19);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (102,  NULL, '1', 102, NULL, '0', "Сапоги");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (102, 19);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (103,  NULL, '1', 103, NULL, '0', "Босоножки");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (103, 19);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (104,  NULL, '1', 104, NULL, '0', "Балетки");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (104, 19);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (105,  NULL, '1', 105, NULL, '0', "Кеды");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (105, 19);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (106,  NULL, '1', 106, NULL, '0', "Кросовки повседневные");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (106, 19);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (107,  NULL, '1', 107, NULL, '0', "Кросовки беговые");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (107, 19);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (108,  NULL, '1', 108, NULL, '0', "Домашняя обувь");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (108, 19);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (20,  NULL, '1', 20, NULL, '0', "Мужская");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (20, 2);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (109,  NULL, '1', 109, NULL, '0', "Туфли ");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (109, 20);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (110,  NULL, '1', 110, NULL, '0', "Кросовки повседневные");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (110, 20);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (111,  NULL, '1', 111, NULL, '0', "Кросовки беговые");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (111, 20);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (112,  NULL, '1', 112, NULL, '0', "Кеды");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (112, 20);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (113,  NULL, '1', 113, NULL, '0', "Домашняя обувь");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (113, 20);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (21,  NULL, '1', 21, NULL, '0', "Сумки");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (21, 2);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (114,  NULL, '1', 114, NULL, '0', "Женские сумки");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (114, 21);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (115,  NULL, '1', 115, NULL, '0', "Мужские повседневные");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (115, 21);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (116,  NULL, '1', 116, NULL, '0', "Сумки на колесиках");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (116, 21);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (117,  NULL, '1', 117, NULL, '0', "Спортивные");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (117, 21);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (22,  NULL, '1', 22, NULL, '0', "Аксессуары");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (22, 2);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (118,  NULL, '1', 118, NULL, '0', "Ремень и пояс");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (118, 22);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (119,  NULL, '1', 119, NULL, '0', "Платки");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (119, 22);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (120,  NULL, '1', 120, NULL, '0', "Шарвы");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (120, 22);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (121,  NULL, '1', 121, NULL, '0', "Перчатки");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (121, 22);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (122,  NULL, '1', 122, NULL, '0', "Палантины");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (122, 22);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (123,  NULL, '1', 123, NULL, '0', "Женские головные уборы");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (123, 22);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (124,  NULL, '1', 124, NULL, '0', "Мужские головные уборы");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (124, 22);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (3,  NULL, '1', 3, NULL, '0', "Дети");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (3, 0);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (23,  NULL, '1', 23, NULL, '0', "Игрушки");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (23, 3);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (125,  NULL, '1', 125, NULL, '0', "Игрушки");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (125, 23);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (126,  NULL, '1', 126, NULL, '0', "Игрушки Мягкие");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (126, 23);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (127,  NULL, '1', 127, NULL, '0', "Игрушки развивающие");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (127, 23);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (128,  NULL, '1', 128, NULL, '0', "Игрушки с пультом ДУ");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (128, 23);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (129,  NULL, '1', 129, NULL, '0', "Одежда для девочек");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (129, 23);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (130,  NULL, '1', 130, NULL, '0', "Одежда для мальчиков");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (130, 23);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (131,  NULL, '1', 131, NULL, '0', "Одежда для малышей");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (131, 23);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (132,  NULL, '1', 132, NULL, '0', "Обувь");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (132, 23);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (133,  NULL, '1', 133, NULL, '0', "Кроватки и коляски");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (133, 23);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (134,  NULL, '1', 134, NULL, '0', "Велосипеды и прочий транспорт");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (134, 23);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (135,  NULL, '1', 135, NULL, '0', "Детский текстиль");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (135, 23);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (136,  NULL, '1', 136, NULL, '0', "Удобства для матери");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (136, 23);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (137,  NULL, '1', 137, NULL, '0', "Одежда для беременных");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (137, 23);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (138,  NULL, '1', 138, NULL, '0', "Уход за ребенком");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (138, 23);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (4,  NULL, '1', 4, NULL, '0', "Мобильная техника");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (4, 0);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (24,  NULL, '1', 24, NULL, '0', "Смартфоны");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (24, 4);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (139,  NULL, '1', 139, NULL, '0', "Диагональ до 5");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (139, 24);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (140,  NULL, '1', 140, NULL, '0', "Диагональ более 5");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (140, 24);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (141,  NULL, '1', 141, NULL, '0', "Apple");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (141, 24);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (142,  NULL, '1', 142, NULL, '0', "Samsung");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (142, 24);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (25,  NULL, '1', 25, NULL, '0', "Сумки и чехлы");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (25, 4);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (143,  NULL, '1', 143, NULL, '0', "Чехлы-бамперы");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (143, 25);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (144,  NULL, '1', 144, NULL, '0', "Водонепроницаемые чехлы");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (144, 25);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (145,  NULL, '1', 145, NULL, '0', "Кожаные чехлы");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (145, 25);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (146,  NULL, '1', 146, NULL, '0', "Алюминиевые чехлы");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (146, 25);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (147,  NULL, '1', 147, NULL, '0', "Чехлы со стразами");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (147, 25);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (26,  NULL, '1', 26, NULL, '0', "Остальное");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (26, 4);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (148,  NULL, '1', 148, NULL, '0', "Планшеты");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (148, 26);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (149,  NULL, '1', 149, NULL, '0', "Смарт-часы");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (149, 26);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (150,  NULL, '1', 150, NULL, '0', "Ноутбуки");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (150, 26);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (151,  NULL, '1', 151, NULL, '0', "Плееры");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (151, 26);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (152,  NULL, '1', 152, NULL, '0', "Внешние батареи для зарядки");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (152, 26);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (153,  NULL, '1', 153, NULL, '0', "Защитные пленки");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (153, 26);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (154,  NULL, '1', 154, NULL, '0', "Зарядные устройства");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (154, 26);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (5,  NULL, '1', 5, NULL, '0', "Техника");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (5, 0);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (27,  NULL, '1', 27, NULL, '0', "Бытовая техника");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (27, 5);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (155,  NULL, '1', 155, NULL, '0', "Холодильники");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (155, 27);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (156,  NULL, '1', 156, NULL, '0', "Стиральные машины");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (156, 27);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (157,  NULL, '1', 157, NULL, '0', "Электроплиты");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (157, 27);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (158,  NULL, '1', 158, NULL, '0', "Газовые плиты");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (158, 27);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (159,  NULL, '1', 159, NULL, '0', "Микроволновки");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (159, 27);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (160,  NULL, '1', 160, NULL, '0', "Комбайны и блендеры");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (160, 27);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (161,  NULL, '1', 161, NULL, '0', "Вытяжки");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (161, 27);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (162,  NULL, '1', 162, NULL, '0', "Посудомоечные машины");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (162, 27);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (163,  NULL, '1', 163, NULL, '0', "Духовые шкафы");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (163, 27);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (164,  NULL, '1', 164, NULL, '0', "Пароварки");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (164, 27);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (165,  NULL, '1', 165, NULL, '0', "Гриль");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (165, 27);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (28,  NULL, '1', 28, NULL, '0', "Техника для дома");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (28, 5);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (166,  NULL, '1', 166, NULL, '0', "Телевизоры");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (166, 28);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (167,  NULL, '1', 167, NULL, '0', "Домашние кинотеатры");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (167, 28);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (168,  NULL, '1', 168, NULL, '0', "Видеопроигрователи");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (168, 28);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (169,  NULL, '1', 169, NULL, '0', "Музыкальные центры");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (169, 28);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (29,  NULL, '1', 29, NULL, '0', "Компьютерная техника");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (29, 5);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (170,  NULL, '1', 170, NULL, '0', "Корпуса");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (170, 29);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (171,  NULL, '1', 171, NULL, '0', "жесткие диски");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (171, 29);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (172,  NULL, '1', 172, NULL, '0', "процессоры");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (172, 29);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (173,  NULL, '1', 173, NULL, '0', "оперативная память ");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (173, 29);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (174,  NULL, '1', 174, NULL, '0', "видео карты");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (174, 29);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (175,  NULL, '1', 175, NULL, '0', "метеринские карты");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (175, 29);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (176,  NULL, '1', 176, NULL, '0', "клавиатуры мыши");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (176, 29);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (177,  NULL, '1', 177, NULL, '0', "Мониторы");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (177, 29);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (6,  NULL, '1', 6, NULL, '0', "Красота и здоровье");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (6, 0);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (30,  NULL, '1', 30, NULL, '0', "Макияж");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (30, 6);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (178,  NULL, '1', 178, NULL, '0', "Косметика");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (178, 30);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (179,  NULL, '1', 179, NULL, '0', "Для глаз");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (179, 30);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (180,  NULL, '1', 180, NULL, '0', "Инструменты и аксессуары");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (180, 30);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (181,  NULL, '1', 181, NULL, '0', "Для лица");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (181, 30);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (182,  NULL, '1', 182, NULL, '0', "Для губ");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (182, 30);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (183,  NULL, '1', 183, NULL, '0', "Наборы для макияжа");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (183, 30);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (31,  NULL, '1', 31, NULL, '0', "Маникюр и инструменты");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (31, 6);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (184,  NULL, '1', 184, NULL, '0', "Дизайн ногтей");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (184, 31);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (185,  NULL, '1', 185, NULL, '0', "Наращивание ногтей");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (185, 31);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (186,  NULL, '1', 186, NULL, '0', "Лаки для ногтей");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (186, 31);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (187,  NULL, '1', 187, NULL, '0', "Инструменты для маникюра");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (187, 31);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (32,  NULL, '1', 32, NULL, '0', "Уход за волосами и укладка");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (32, 6);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (188,  NULL, '1', 188, NULL, '0', "Выпрямляющие утюжки");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (188, 32);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (189,  NULL, '1', 189, NULL, '0', "Бигуди");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (189, 32);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (190,  NULL, '1', 190, NULL, '0', "Окрашивание волос");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (190, 32);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (191,  NULL, '1', 191, NULL, '0', "Средства от выпадения волос");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (191, 32);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (33,  NULL, '1', 33, NULL, '0', "Здоровье и гигиена");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (33, 6);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (192,  NULL, '1', 192, NULL, '0', "Бритьё и эпиляция");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (192, 33);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (193,  NULL, '1', 193, NULL, '0', "Интимные товары");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (193, 33);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (7,  NULL, '1', 7, NULL, '0', "Очки часы и украшения");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (7, 0);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (34,  NULL, '1', 34, NULL, '0', "Очки");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (34, 7);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (194,  NULL, '1', 194, NULL, '0', "Солнцезащитные Женские");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (194, 34);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (195,  NULL, '1', 195, NULL, '0', "Солнцезащитные Мужские");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (195, 34);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (196,  NULL, '1', 196, NULL, '0', "Футляры");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (196, 34);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (35,  NULL, '1', 35, NULL, '0', "Часы");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (35, 7);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (197,  NULL, '1', 197, NULL, '0', "Смарт часы");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (197, 35);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (198,  NULL, '1', 198, NULL, '0', "Мужские циферблат  электронный ");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (198, 35);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (199,  NULL, '1', 199, NULL, '0', "Мужские циферблат стрелки");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (199, 35);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (36,  NULL, '1', 36, NULL, '0', "Украшения");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (36, 7);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (8,  NULL, '1', 8, NULL, '0', "Для дома и сада");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (8, 0);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (37,  NULL, '1', 37, NULL, '0', "Мебель");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (37, 8);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (200,  NULL, '1', 200, NULL, '0', "Кухня");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (200, 37);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (201,  NULL, '1', 201, NULL, '0', "Гостинная");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (201, 37);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (202,  NULL, '1', 202, NULL, '0', "Спальня");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (202, 37);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (203,  NULL, '1', 203, NULL, '0', "Детская");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (203, 37);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (204,  NULL, '1', 204, NULL, '0', "Туалет и Ванная");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (204, 37);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (205,  NULL, '1', 205, NULL, '0', "Дизайнерская");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (205, 37);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (38,  NULL, '1', 38, NULL, '0', "Ремонт и отделка");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (38, 8);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (206,  NULL, '1', 206, NULL, '0', "Плитка");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (206, 38);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (207,  NULL, '1', 207, NULL, '0', "Ламинат");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (207, 38);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (208,  NULL, '1', 208, NULL, '0', "Паркет");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (208, 38);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (209,  NULL, '1', 209, NULL, '0', "Обои");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (209, 38);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (210,  NULL, '1', 210, NULL, '0', "Элементы дизайна");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (210, 38);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (211,  NULL, '1', 211, NULL, '0', "Линолеум");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (211, 38);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (39,  NULL, '1', 39, NULL, '0', "Свет");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (39, 8);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (212,  NULL, '1', 212, NULL, '0', "Люстры");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (212, 39);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (213,  NULL, '1', 213, NULL, '0', "Светильники ");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (213, 39);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (214,  NULL, '1', 214, NULL, '0', "Светильники Настольные");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (214, 39);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (215,  NULL, '1', 215, NULL, '0', "Уличные светильники");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (215, 39);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (216,  NULL, '1', 216, NULL, '0', "Светодиодное освещение");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (216, 39);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (40,  NULL, '1', 40, NULL, '0', "Кухня и хоз товары");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (40, 8);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (217,  NULL, '1', 217, NULL, '0', "Посуда");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (217, 40);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (218,  NULL, '1', 218, NULL, '0', "Уборка");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (218, 40);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (41,  NULL, '1', 41, NULL, '0', "Сад");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (41, 8);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (219,  NULL, '1', 219, NULL, '0', "Семена");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (219, 41);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (220,  NULL, '1', 220, NULL, '0', "Саженцы");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (220, 41);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (221,  NULL, '1', 221, NULL, '0', "Садовый деко");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (221, 41);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (222,  NULL, '1', 222, NULL, '0', "Полив");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (222, 41);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (223,  NULL, '1', 223, NULL, '0', "Садовый инструмент");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (223, 41);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (9,  NULL, '1', 9, NULL, '0', "Спорт, отдых и хоби");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (9, 0);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (42,  NULL, '1', 42, NULL, '0', "Лето");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (42, 9);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (224,  NULL, '1', 224, NULL, '0', "Футбол");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (224, 42);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (225,  NULL, '1', 225, NULL, '0', "Бег");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (225, 42);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (226,  NULL, '1', 226, NULL, '0', "Ролики");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (226, 42);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (227,  NULL, '1', 227, NULL, '0', "Большой тенис");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (227, 42);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (228,  NULL, '1', 228, NULL, '0', "Настольный тенис");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (228, 42);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (229,  NULL, '1', 229, NULL, '0', "Волейбол");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (229, 42);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (230,  NULL, '1', 230, NULL, '0', "Бодибилдинг");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (230, 42);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (231,  NULL, '1', 231, NULL, '0', "Велосипед");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (231, 42);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (43,  NULL, '1', 43, NULL, '0', "Зима");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (43, 9);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (232,  NULL, '1', 232, NULL, '0', "Лыжи");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (232, 43);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (233,  NULL, '1', 233, NULL, '0', "Горные лыжи");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (233, 43);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (234,  NULL, '1', 234, NULL, '0', "Сноуборд");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (234, 43);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (235,  NULL, '1', 235, NULL, '0', "Хокей");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (235, 43);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (236,  NULL, '1', 236, NULL, '0', "Коньки");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (236, 43);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (44,  NULL, '1', 44, NULL, '0', "Детский спорт");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (44, 9);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (10,  NULL, '1', 10, NULL, '0', "Авто - мото");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (10, 0);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (45,  NULL, '1', 45, NULL, '0', "Электроника");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (45, 10);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (237,  NULL, '1', 237, NULL, '0', "Видеорегистраторы");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (237, 45);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (238,  NULL, '1', 238, NULL, '0', "GPS-навигаторы");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (238, 45);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (239,  NULL, '1', 239, NULL, '0', "Видеоплееры");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (239, 45);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (240,  NULL, '1', 240, NULL, '0', "Аудиоплееры");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (240, 45);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (241,  NULL, '1', 241, NULL, '0', "Радио");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (241, 45);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (242,  NULL, '1', 242, NULL, '0', "Системы безопасности");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (242, 45);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (243,  NULL, '1', 243, NULL, '0', "Детекторы для авто");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (243, 45);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (46,  NULL, '1', 46, NULL, '0', "Аксессуары");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (46, 10);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (244,  NULL, '1', 244, NULL, '0', "Стайлинг автомобиля");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (244, 46);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (245,  NULL, '1', 245, NULL, '0', "Ковры и коврики");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (245, 46);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (246,  NULL, '1', 246, NULL, '0', "Чехлы на руль");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (246, 46);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (247,  NULL, '1', 247, NULL, '0', "Хранение и организация");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (247, 46);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (248,  NULL, '1', 248, NULL, '0', "Прикуриватели");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (248, 46);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (249,  NULL, '1', 249, NULL, '0', "Внешнее освещение");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (249, 46);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (250,  NULL, '1', 250, NULL, '0', "Внутренней освещение");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (250, 46);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (251,  NULL, '1', 251, NULL, '0', "Освежители воздуха");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (251, 46);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (252,  NULL, '1', 252, NULL, '0', "Чехлы для автомобиля");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (252, 46);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (253,  NULL, '1', 253, NULL, '0', "Зарядные ");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (253, 46);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (11,  NULL, '1', 11, NULL, '0', "Игры филмы развлечение");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (11, 0);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (47,  NULL, '1', 47, NULL, '0', "Видео Игры");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (47, 11);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (254,  NULL, '1', 254, NULL, '0', "PleyStation");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (254, 47);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (255,  NULL, '1', 255, NULL, '0', "Xbox");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (255, 47);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (256,  NULL, '1', 256, NULL, '0', "Компьютеры");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (256, 47);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (12,  NULL, '1', 12, NULL, '0', "Еда напитки");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (12, 0);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (48,  NULL, '1', 48, NULL, '0', "Доставка готовой еды");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (48, 12);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (257,  NULL, '1', 257, NULL, '0', "Пицца");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (257, 48);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (258,  NULL, '1', 258, NULL, '0', "Японская кухня");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (258, 48);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (259,  NULL, '1', 259, NULL, '0', "Китайская кухня");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (259, 48);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (260,  NULL, '1', 260, NULL, '0', "Европейская");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (260, 48);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (261,  NULL, '1', 261, NULL, '0', "Гриль");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (261, 48);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (262,  NULL, '1', 262, NULL, '0', "Бургеры");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (262, 48);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (13,  NULL, '1', 13, NULL, '0', "Офисные товары");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (13, 0);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (49,  NULL, '1', 49, NULL, '0', "Мебель");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (49, 13);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (50,  NULL, '1', 50, NULL, '0', "Принадлежности");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (50, 13);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (51,  NULL, '1', 51, NULL, '0', "Электроника");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (51, 13);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (14,  NULL, '1', 14, NULL, '0', "Книги и учеба");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (14, 0);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (15,  NULL, '1', 15, NULL, '0', "Подарки, творчество праздник");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (15, 0);
INSERT INTO `comiron`.`category` (`id`,  `category_id`, `visible`, `ordr`, `thumbnail_url`, `ispopular`, `name_ru`) VALUES (,  NULL, '1', , NULL, '0', "");
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
insert into `comiron`.`category_parent` (`id`, `category_id`) values (, );
