ALTER TABLE  product ADD weight INT( 11 ) NULL DEFAULT  0,
ADD  volume INT( 11 ) NULL DEFAULT  0,
ADD  w INT( 11 ) NULL DEFAULT  0,
ADD  h INT( 11 ) NULL DEFAULT  0,
ADD  d INT( 11 ) NULL DEFAULT  0,
ADD  sklad INT( 11 ) NULL DEFAULT  0;

ALTER TABLE  product CHANGE  weight  weight FLOAT( 11 ) NULL DEFAULT  0,
CHANGE  volume  volume FLOAT( 11 ) NULL DEFAULT  0,
CHANGE  w  w FLOAT( 11 ) NULL DEFAULT  0,
CHANGE  h  h FLOAT( 11 ) NULL DEFAULT  0,
CHANGE  d  d FLOAT( 11 ) NULL DEFAULT  0,
CHANGE  sklad  sklad FLOAT( 11 ) NULL DEFAULT  0;

ALTER TABLE product ADD INDEX (sklad);

ALTER TABLE  product ADD  discount INT NOT NULL DEFAULT  0;